library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.RISCV_package.all;
use work.mi_package.all;

entity Fetch is
	generic(
		-- Users can add generic parameters here

		-- User parameters ends
		C_M_TARGET_SLAVE_BASE_ADDR : slv := x"00000000"; -- Base address of targeted slave
		C_M_AXI_BURST_LEN : integer := 1; -- Burst Length. Supports 1, 2, 4, 8, 16, 32, 64, 128, 256 burst lengths
		C_M_AXI_ID_WIDTH : integer := 1; -- Thread ID Width
		C_M_AXI_ADDR_WIDTH : integer := MEM_ADDR_BITS; -- Width of Address Bus
		C_M_AXI_DATA_WIDTH : integer := 32; -- Width of Data Bus
		C_M_AXI_AWUSER_WIDTH : integer := 0; -- Width of User Write Address Bus
		C_M_AXI_ARUSER_WIDTH : integer := 0; -- Width of User Read Address Bus
		C_M_AXI_WUSER_WIDTH : integer := 0; -- Width of User Write Data Bus
		C_M_AXI_RUSER_WIDTH : integer := 0; -- Width of User Read Data Bus
		C_M_AXI_BUSER_WIDTH : integer := 0 -- Width of User Response Bus
	);
	port(
		-- Users can add ports here. These are SUGGESTED user ports.
		Start_read : in sl; -- Initiate AXI read transaction
		Read_address : in slv(C_M_AXI_ADDR_WIDTH - 1 downto 0); -- address to read from
		Read_Done : out sl; -- Asserts when transaction is complete
		Read_Data : out slv(C_M_AXI_DATA_WIDTH - 1 downto 0); -- Data that was read (modify as needed)
		Error : out sl; -- Asserts when ERROR is detected
		clk : in sl; -- Global Clock Signal.
		reset : in sl; -- Global Reset Singal. This Signal is Active Low
		-- User ports ends
		-- AXI Read Address Channel
		M_AXI_ARID : out slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Master Interface Read Address.
		M_AXI_ARADDR : out slv(C_M_AXI_ADDR_WIDTH - 1 downto 0); -- Read address. This signal indicates the initial address of a read burst transaction.
		M_AXI_ARLEN : out slv(7 downto 0); -- Burst length. The burst length gives the exact number of transfers in a burst
		M_AXI_ARSIZE : out slv(2 downto 0); -- Burst size. This signal indicates the size of each transfer in the burst
		M_AXI_ARBURST : out slv(1 downto 0); -- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
		M_AXI_ARLOCK : out sl; -- Lock type. Provides additional information about the atomic characteristics of the transfer.
		M_AXI_ARCACHE : out slv(3 downto 0); -- Memory type. This signal indicates how transactions are required to progress through a system.
		M_AXI_ARPROT : out slv(2 downto 0); -- Protection type. This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.
		M_AXI_ARQOS : out slv(3 downto 0); -- Quality of Service, QoS identifier sent for each read transaction
		--M_AXI_ARUSER	: out slv(C_M_AXI_ARUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
		M_AXI_ARVALID : out sl; -- Write address valid. This signal indicates that the channel is signaling valid read address and control information
		M_AXI_ARREADY : in sl; -- Read address ready. This signal indicates that the slave is ready to accept an address and associated control signals
		-- AXI Read Data Channel
		M_AXI_RID : in slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave.
		M_AXI_RDATA : in slv(C_M_AXI_DATA_WIDTH - 1 downto 0); -- Master Read Data
		M_AXI_RRESP : in slv(1 downto 0); -- Read response. This signal indicates the status of the read transfer
		M_AXI_RLAST : in sl; -- Read last. This signal indicates the last transfer in a read burst
		--M_AXI_RUSER	: in slv(C_M_AXI_RUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
		M_AXI_RVALID : in sl; -- Read valid. This signal indicates that the channel is signaling the required read data.
		M_AXI_RREADY : out sl -- Read ready. This signal indicates that the master can accept the read data and response information.
	);
end Fetch;

architecture implementation of Fetch is
	type state_t is (IDLE, EMPTY_FIFO, START, ACCEPTING);
	signal cur_state, next_state_i, next_state_final : state_t;
	signal IDLE_next, EMPTY_FIFO_next, START_next, ACCEPTING_next : state_t;
	signal FIFO_out : slv(2 * XLEN - 1 downto 0);
	signal FIFO_wdata : slv(2 * XLEN - 1 downto 0);
	signal FIFO_wen, FIFO_ren, FIFO_empty, FIFO_full : sl;
	signal Read_Done_i, IR_en, hit : sl;
	signal IR, next_IR : slv(XLEN - 1 downto 0);
	signal next_transfer_count : unsigned(1 downto 0) := "00";
	signal transfer_count : unsigned(1 downto 0) := "00";
	signal address : slv(XLEN - 1 downto 0) := (others => '0');
	signal ctrl : slv(1 downto 0);
begin
	--Instruction FIFO -- data = FIFO_out(63 downto 32) -- address = FIFO_out(31 downto 0);
	IR <= next_IR when rising_edge(clk);
	next_IR <= (others => '0') when reset = '1' else FIFO_out(63 downto 32) when IR_en = '1' else IR;

	FIFO : entity work.generic_FIFO(behavioral)
		generic map(bits => 2 * XLEN, depth => PRE_FETCH_SIZE) --change depth if wanna be more betterer maybe in trial and error
		port map(clk => clk, rst => reset,
		         wdata => FIFO_wdata,
		         wen => FIFO_wen,
		         ren => FIFO_ren,
		         rdata => FIFO_out,
		         empty => FIFO_empty,
		         full => FIFO_full);
	FIFO_wdata <= M_AXI_RDATA & slv(unsigned(address) + resize(unsigned(transfer_count) & "00", 32)); --need to track whcih address in thing 

	transfer_count <= next_transfer_count when rising_edge(clk);
	next_transfer_count <= "00" when (reset = '1' or cur_state = IDLE) else transfer_count + 1 when FIFO_wen = '1' else transfer_count;

	------------------------------
	-- Read Address Channel
	------------------------------
	----------------------------------
	--Read Data Channel
	----------------------------------
	--constant-ish outputs
	M_AXI_ARID <= (others => '0');
	M_AXI_ARADDR <= address;
	M_AXI_ARLEN <= slv(to_unsigned(PRE_FETCH_SIZE - 1, 8));
	M_AXI_ARSIZE <= "010";
	M_AXI_ARBURST <= "01"; --INCR
	M_AXI_ARLOCK <= '0';
	M_AXI_ARCACHE <= "0011"; --Normal Non-cachable Bufferable
	M_AXI_ARPROT <= "100";
	M_AXI_ARQOS <= "0000";

	--memory
	cur_state <= next_state_final when rising_edge(clk);
	next_state_final <= IDLE when reset = '1' else next_state_i;
	--next state
	with cur_state select next_state_i <=
		IDLE_next when IDLE,
		EMPTY_FIFO_next when EMPTY_FIFO,
		START_next when START,
		ACCEPTING_next when ACCEPTING;

	ctrl <= FIFO_empty & not hit;
	with ctrl select IDLE_next <=
		IDLE when "00",
		EMPTY_FIFO when "01",
		START when others; --"1x"

	--	IDLE_next <= START when (FIFO_empty = '1') else
	--	             EMPTY_FIFO when (not (Read_address = FIFO_out(31 downto 0))) else 
	--	             IDLE;
	EMPTY_FIFO_next <= START when FIFO_empty = '1' else EMPTY_FIFO;
	START_next <= ACCEPTING when M_AXI_ARREADY = '1' else START;
	ACCEPTING_next <= IDLE when M_AXI_RLAST = '1' else ACCEPTING;

	--internal signals
	FIFO_wen <= '1' when (cur_state = ACCEPTING and M_AXI_RVALID = '1') else '0';
	FIFO_ren <= '1' when cur_state = EMPTY_FIFO or (Read_Done_i = '1' and Start_read = '1') else '0';
	IR_en <= '1' when hit = '1' and Start_read = '1' else '0';

	--internal latch
	address <= (others => '0') when reset = '1' else Read_address when cur_state = IDLE else address;

	--Bus outputs
	M_AXI_ARVALID <= '1' when cur_state = START else '0';
	M_AXI_RREADY <= '1' when cur_state = ACCEPTING else '0';
	--external outputs
	hit <= '1' when Read_address = FIFO_out(31 downto 0) else '0';
	Read_Done_i <= '1' when hit = '1' and FIFO_empty = '0' else '0';
	Read_Done <= Read_Done_i;
	Error <= '1' when M_AXI_RRESP(1) = '1' else '0'; --both errors have RRESP bit 1 as high
	Read_Data <= IR;

end implementation;
