library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.RISCV_package.all;

entity Fetch is
	generic(
		-- Users can add generic parameters here

		-- User parameters ends
		C_M_TARGET_SLAVE_BASE_ADDR : slv := x"00000000"; -- Base address of targeted slave
		C_M_AXI_BURST_LEN : integer := 1; -- Burst Length. Supports 1, 2, 4, 8, 16, 32, 64, 128, 256 burst lengths
		C_M_AXI_ID_WIDTH : integer := 1; -- Thread ID Width
		C_M_AXI_ADDR_WIDTH : integer := MEM_ADDR_BITS; -- Width of Address Bus
		C_M_AXI_DATA_WIDTH : integer := 32; -- Width of Data Bus
		C_M_AXI_AWUSER_WIDTH : integer := 0; -- Width of User Write Address Bus
		C_M_AXI_ARUSER_WIDTH : integer := 0; -- Width of User Read Address Bus
		C_M_AXI_WUSER_WIDTH : integer := 0; -- Width of User Write Data Bus
		C_M_AXI_RUSER_WIDTH : integer := 0; -- Width of User Read Data Bus
		C_M_AXI_BUSER_WIDTH : integer := 0 -- Width of User Response Bus
	);
	port(
		-- Users can add ports here.
		clk : in sl; -- Global Clock Signal.
		reset : in sl; -- Global Reset Singal. This Signal is Active High
		addr_valid : in sl;
		address : in slv(C_M_AXI_ADDR_WIDTH - 1 downto 0);
		data_valid : out sl;
		data : out slv(C_M_AXI_DATA_WIDTH - 1 downto 0);
		error : out sl;
		-- User ports ends
		-- AXI Read Address Channel
		M_AXI_ARID : out slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Master Interface Read Address.
		M_AXI_ARADDR : out slv(C_M_AXI_ADDR_WIDTH - 1 downto 0); -- Read address. This signal indicates the initial address of a read burst transaction.
		M_AXI_ARLEN : out slv(7 downto 0); -- Burst length. The burst length gives the exact number of transfers in a burst
		M_AXI_ARSIZE : out slv(2 downto 0); -- Burst size. This signal indicates the size of each transfer in the burst
		M_AXI_ARBURST : out slv(1 downto 0); -- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
		M_AXI_ARLOCK : out sl; -- Lock type. Provides additional information about the atomic characteristics of the transfer.
		M_AXI_ARCACHE : out slv(3 downto 0); -- Memory type. This signal indicates how transactions are required to progress through a system.
		M_AXI_ARPROT : out slv(2 downto 0); -- Protection type. This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.
		M_AXI_ARQOS : out slv(3 downto 0); -- Quality of Service, QoS identifier sent for each read transaction
		--M_AXI_ARUSER	: out slv(C_M_AXI_ARUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
		M_AXI_ARVALID : out sl; -- Write address valid. This signal indicates that the channel is signaling valid read address and control information
		M_AXI_ARREADY : in sl; -- Read address ready. This signal indicates that the slave is ready to accept an address and associated control signals
		-- AXI Read Data Channel
		M_AXI_RID : in slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave.
		M_AXI_RDATA : in slv(C_M_AXI_DATA_WIDTH - 1 downto 0); -- Master Read Data
		M_AXI_RRESP : in slv(1 downto 0); -- Read response. This signal indicates the status of the read transfer
		M_AXI_RLAST : in sl; -- Read last. This signal indicates the last transfer in a read burst
		--M_AXI_RUSER	: in slv(C_M_AXI_RUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
		M_AXI_RVALID : in sl; -- Read valid. This signal indicates that the channel is signaling the required read data.
		M_AXI_RREADY : out sl -- Read ready. This signal indicates that the master can accept the read data and response information.
	);
end Fetch;

architecture implementation of Fetch is
	constant FIFO_DEPTH : integer := 2 * PRE_FETCH_BURST_SIZE;
	constant FIFO_DEPTH_BITS : integer := clog2(FIFO_DEPTH);

	type state_t is (IDLE, HALF_SEND_ADDR, MISS_SEND_ADDR, HALF_ACCEPTING, MISS_ACCEPTING);
	signal cur_state, next_state_i, next_state_final, prev_state, prev_state_final : state_t;
	signal IDLE_next, HALF_SEND_ADDR_next, MISS_SEND_ADDR_next, HALF_ACCEPTING_next, MISS_ACCEPTING_next : state_t;
	signal FIFO_out : slv(2 * XLEN - 1 downto 0);
	signal FIFO_wdata : slv(2 * XLEN - 1 downto 0);
	signal FIFO_rst, FIFO_wen, FIFO_ren, FIFO_empty, FIFO_full, FIFO_below_threshold : sl;
	signal next_transfer_count : unsigned(FIFO_DEPTH_BITS - 1 downto 0) := (others => '0');
	signal transfer_count : unsigned(FIFO_DEPTH_BITS - 1 downto 0) := (others => '0');
	signal axi_address, next_axi_address, axi_addr_plus_1x, axi_addr_plus_2x : slv(C_M_AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
	signal send_addr, accepting, addr_hit, addr_miss : sl;
	signal M_AXI_RREADY_i : sl;
begin
	--FIFO format: data = FIFO_out(63 downto 32), address = FIFO_out(31 downto 0);
	FIFO_wdata <= M_AXI_RDATA & slv(unsigned(axi_address) + resize(unsigned(transfer_count) & "00", 32)); --need to track whcih address in thing 
	FIFO : entity work.generic_FIFO(behavioral)
		generic map(bits => 2 * XLEN, depth => FIFO_DEPTH) --change depth if wanna be more betterer maybe in trial and error
		port map(clk => clk, rst => reset or FIFO_rst,
		         wdata => FIFO_wdata,
		         wen => FIFO_wen,
		         ren => FIFO_ren,
		         threshold => slv(to_unsigned(PRE_FETCH_BURST_SIZE - 1, FIFO_DEPTH_BITS)),
		         rdata => FIFO_out,
		         empty => FIFO_empty,
		         full => FIFO_full,
		         below_threshold => FIFO_below_threshold
		        );

	transfer_count <= next_transfer_count when rising_edge(clk);
	next_transfer_count <= (others => '0') when cur_state = IDLE else
	                       transfer_count + 1 when FIFO_wen = '1' else
	                       transfer_count;

	------------------------------
	-- Read Address Channel
	------------------------------
	----------------------------------
	--Read Data Channel
	----------------------------------
	--constant-ish outputs
	M_AXI_ARID <= (others => '0');
	M_AXI_ARADDR <= axi_address;
	M_AXI_ARLEN <= slv(to_unsigned(2 * PRE_FETCH_BURST_SIZE - 1, 8)) when cur_state = MISS_SEND_ADDR else
	               slv(to_unsigned(PRE_FETCH_BURST_SIZE - 1, 8));
	M_AXI_ARSIZE <= "010";
	M_AXI_ARBURST <= "01"; --INCR
	M_AXI_ARLOCK <= '0';
	M_AXI_ARCACHE <= "0011"; --Normal Non-cachable Bufferable
	M_AXI_ARPROT <= "100";
	M_AXI_ARQOS <= "0000";

	--memory
	cur_state <= next_state_final when rising_edge(clk);
	next_state_final <= IDLE when reset = '1' else next_state_i;

	prev_state <= prev_state_final when rising_edge(clk);
	prev_state_final <= IDLE when reset = '1' else cur_state;

	axi_address <= next_axi_address when rising_edge(clk);
	next_axi_address <= (others => '0') when reset = '1' else
	                    address when cur_state = MISS_SEND_ADDR and prev_state = IDLE else
	                    axi_addr_plus_2x when (cur_state = IDLE and prev_state = MISS_ACCEPTING) else
	                    axi_addr_plus_1x when (cur_state = IDLE and prev_state = HALF_ACCEPTING) else
	                    axi_address;
	axi_addr_plus_1x <= slv(unsigned(axi_address) + to_unsigned(4 * PRE_FETCH_BURST_SIZE, axi_address'length));
	axi_addr_plus_2x <= slv(unsigned(axi_address) + to_unsigned(8 * PRE_FETCH_BURST_SIZE, axi_address'length));
	--next state
	with cur_state select next_state_i <=
		IDLE_next when IDLE,
		HALF_SEND_ADDR_next when HALF_SEND_ADDR,
		MISS_SEND_ADDR_next when MISS_SEND_ADDR,
		HALF_ACCEPTING_next when HALF_ACCEPTING,
		MISS_ACCEPTING_next when MISS_ACCEPTING;

	IDLE_next <= MISS_SEND_ADDR when (addr_miss = '1') else
	             HALF_SEND_ADDR when (FIFO_below_threshold = '1') else
	             IDLE;
	MISS_SEND_ADDR_next <= MISS_ACCEPTING when (M_AXI_ARREADY = '1') else MISS_SEND_ADDR;
	HALF_SEND_ADDR_next <= HALF_ACCEPTING when (M_AXI_ARREADY = '1') else HALF_SEND_ADDR;
	MISS_ACCEPTING_next <= IDLE when M_AXI_RLAST = '1' else MISS_ACCEPTING;
	HALF_ACCEPTING_next <= IDLE when M_AXI_RLAST = '1' else HALF_ACCEPTING;

	--internal signals
	send_addr <= '1' when (cur_state = HALF_SEND_ADDR or cur_state = MISS_SEND_ADDR) else '0';
	accepting <= '1' when (cur_state = HALF_ACCEPTING or cur_state = MISS_ACCEPTING) else '0';
	FIFO_wen <= '1' when (M_AXI_RREADY_i = '1' and M_AXI_RVALID = '1') else '0';
	FIFO_ren <= addr_hit;
	FIFO_rst <= '1' when (cur_state = IDLE and IDLE_next = MISS_SEND_ADDR) else '0'; --might be long for timing

	addr_hit <= '1' when (addr_valid = '1' and address = FIFO_out(31 downto 0) and FIFO_empty = '0') else '0';
	addr_miss <= not addr_hit and addr_valid;

	--Bus outputs
	M_AXI_ARVALID <= send_addr;
	M_AXI_RREADY_i <= send_addr or accepting;
	M_AXI_RREADY <= M_AXI_RREADY_i;

	--external outputs
	error <= '1' when M_AXI_RRESP(1) = '1' or (FIFO_wen = '1' and FIFO_full = '1') else '0';
	data <= FIFO_out(63 downto 32);
	data_valid <= addr_hit;

end implementation;
