library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.RISCV_package.all;
use work.mi_package.all;

entity Load_Store is
	generic(
		-- User parameters ends
		C_M_TARGET_SLAVE_BASE_ADDR : slv := x"00000000"; -- Base address of targeted slave
		C_M_AXI_BURST_LEN : integer := 1; -- Burst Length. Supports 1, 2, 4, 8, 16, 32, 64, 128, 256 burst lengths
		C_M_AXI_ID_WIDTH : integer := 1; -- Thread ID Width
		C_M_AXI_ADDR_WIDTH : integer := MEM_ADDR_BITS; -- Width of Address Bus
		C_M_AXI_DATA_WIDTH : integer := 32; -- Width of Data Bus
		C_M_AXI_AWUSER_WIDTH : integer := 0; -- Width of User Write Address Bus
		C_M_AXI_ARUSER_WIDTH : integer := 0; -- Width of User Read Address Bus
		C_M_AXI_WUSER_WIDTH : integer := 0; -- Width of User Write Data Bus
		C_M_AXI_RUSER_WIDTH : integer := 0; -- Width of User Read Data Bus
		C_M_AXI_BUSER_WIDTH : integer := 0 -- Width of User Response Bus
	);
	port(
		-- Users can add ports here. These are SUGGESTED user ports.
		start_load, start_store : in sl; -- Initiate AXI read transaction
		load_store_type : in slv(2 downto 0);
		address : in slv(C_M_AXI_ADDR_WIDTH - 1 downto 0); -- address to read from
		store_Data : in slv(C_M_AXI_DATA_WIDTH - 1 downto 0);
		load_done, store_done : out sl; -- Asserts when transaction is complete
		load_data_out : out slv(C_M_AXI_DATA_WIDTH - 1 downto 0); -- Data that was read (modify as needed)
		Error : out sl; -- Asserts when ERROR is detected
		-- User ports ends
		-- Global AXI ports
		M_AXI_ACLK : in sl; -- Global Clock Signal.
		M_AXI_ARESETN : in sl; -- Global Reset Singal. This Signal is Active Low
		-- AXI Read Address Channel
		M_AXI_ARID : out slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Master Interface Read Address.
		M_AXI_ARADDR : out slv(C_M_AXI_ADDR_WIDTH - 1 downto 0); -- Read address. This signal indicates the initial address of a read burst transaction.
		M_AXI_ARLEN : out slv(7 downto 0); -- Burst length. The burst length gives the exact number of transfers in a burst
		M_AXI_ARSIZE : out slv(2 downto 0); -- Burst size. This signal indicates the size of each transfer in the burst
		M_AXI_ARBURST : out slv(1 downto 0); -- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
		M_AXI_ARLOCK : out sl; -- Lock type. Provides additional information about the atomic characteristics of the transfer.
		M_AXI_ARCACHE : out slv(3 downto 0); -- Memory type. This signal indicates how transactions are required to progress through a system.
		M_AXI_ARPROT : out slv(2 downto 0); -- Protection type. This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.
		M_AXI_ARQOS : out slv(3 downto 0); -- Quality of Service, QoS identifier sent for each read transaction
		--M_AXI_ARUSER	: out slv(C_M_AXI_ARUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
		M_AXI_ARVALID : out sl; -- Write address valid. This signal indicates that the channel is signaling valid read address and control information
		M_AXI_ARREADY : in sl; -- Read address ready. This signal indicates that the slave is ready to accept an address and associated control signals
		-- AXI Read Data Channel
		M_AXI_RID : in slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave.
		M_AXI_RDATA : in slv(C_M_AXI_DATA_WIDTH - 1 downto 0); -- Master Read Data
		M_AXI_RRESP : in slv(1 downto 0); -- Read response. This signal indicates the status of the read transfer
		M_AXI_RLAST : in sl; -- Read last. This signal indicates the last transfer in a read burst
		--M_AXI_RUSER	: in slv(C_M_AXI_RUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
		M_AXI_RVALID : in sl; -- Read valid. This signal indicates that the channel is signaling the required read data.
		M_AXI_RREADY : out sl; -- Read ready. This signal indicates that the master can accept the read data and response information.

		-- AXI Write Address Channel
		M_AXI_AWID : out slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Master Interface Write Address ID
		M_AXI_AWADDR : out slv(C_M_AXI_ADDR_WIDTH - 1 downto 0); -- Master Interface Write Address
		M_AXI_AWLEN : out slv(7 downto 0); -- Burst length. The burst length gives the exact number of transfers in a burst
		M_AXI_AWSIZE : out slv(2 downto 0); -- Burst size. This signal indicates the size of each transfer in the burst
		M_AXI_AWBURST : out slv(1 downto 0); -- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
		M_AXI_AWLOCK : out sl; -- Lock type. Provides additional information about the atomic characteristics of the transfer. 
		M_AXI_AWCACHE : out slv(3 downto 0); -- Memory type. This signal indicates how transactions are required to progress through a system.
		M_AXI_AWPROT : out slv(2 downto 0); -- Protection type. This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.
		M_AXI_AWQOS : out slv(3 downto 0); -- Quality of Service, QoS identifier sent for each write transaction.
		--M_AXI_AWUSER	: out slv(C_M_AXI_AWUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the write address channel.
		M_AXI_AWVALID : out sl; -- Write address valid. This signal indicates that the channel is signaling valid write address and control information.
		M_AXI_AWREADY : in sl; -- Write address ready. This signal indicates that the slave is ready to accept an address and associated control signals	
		-- AXI Write Data Channel
		M_AXI_WDATA : out slv(C_M_AXI_DATA_WIDTH - 1 downto 0); -- Master Interface Write Data.
		M_AXI_WSTRB : out slv(C_M_AXI_DATA_WIDTH / 8 - 1 downto 0); -- Write strobes. This signal indicates which byte lanes hold valid data. There is one write strobe bit for each eight bits of the write data bus.
		M_AXI_WLAST : out sl; -- Write last. This signal indicates the last transfer in a write burst.
		--M_AXI_WUSER	: out slv(C_M_AXI_WUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the write data channel.
		M_AXI_WVALID : out sl; -- Write valid. This signal indicates that valid write data and strobes are available
		M_AXI_WREADY : in sl; -- Write ready. This signal indicates that the slave can accept the write data.
		-- AXI Write Response Channel
		M_AXI_BID : in slv(C_M_AXI_ID_WIDTH - 1 downto 0); -- Master Interface Write Response.
		M_AXI_BRESP : in slv(1 downto 0); -- Write response. This signal indicates the status of the write transaction.
		--M_AXI_BUSER	: in slv(C_M_AXI_BUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the write response channel
		M_AXI_BVALID : in sl; -- Write response valid. This signal indicates that the  channel is signaling a valid write response.
		M_AXI_BREADY : out sl -- Response ready. This signal indicates that the master can accept a write response.
	);
end Load_Store;

architecture implementation of Load_Store is
	type state_t is (IDLE, START, WAITING, ACCEPT);
	signal read_cur_state, read_next_state_i, read_next_state_final : state_t;
	signal read_IDLE_next, read_START_next, read_WAITING_next, read_ACCEPT_next : state_t;
	signal store_cur_state, store_next_state_i, store_next_state_final : state_t;
	signal store_IDLE_next, store_START_next, store_WAITING_next, store_ACCEPT_next : state_t;
	signal load_data, next_load_data, pre_load_data : slv(MEM_ADDR_BITS - 1 downto 0);
	signal load_data_en : sl;
	signal byte_mask, half_mask : slv(C_M_AXI_DATA_WIDTH / 8 - 1 downto 0);
begin
	--Load data register
	load_data <= next_load_data when rising_edge(M_AXI_ACLK);
	next_load_data <= (others => '0') when M_AXI_ARESETN = '0' else M_AXI_RDATA when load_data_en = '1' else load_data;
	------------------------------
	-- Read Address Channel
	------------------------------
	----------------------------------
	--Read Data Channel
	----------------------------------
	--constant outputs
	M_AXI_ARID <= (others => '0');
	M_AXI_ARADDR <= address;
	M_AXI_ARLEN <= "00000000";
	M_AXI_ARSIZE <= '0' & load_store_type(1 downto 0);
	M_AXI_ARBURST <= "01";
	M_AXI_ARLOCK <= '0';
	M_AXI_ARCACHE <= "0010";
	M_AXI_ARPROT <= "100";
	M_AXI_ARQOS <= "0000";

	--memory
	read_cur_state <= read_next_state_final when rising_edge(M_AXI_ACLK);
	read_next_state_final <= IDLE when M_AXI_ARESETN = '0' else read_next_state_i;
	--next state
	with read_cur_state select read_next_state_i <=
		read_IDLE_next when IDLE,
		read_START_next when START,
		read_WAITING_next when WAITING,
		read_ACCEPT_next when ACCEPT;

	read_IDLE_next <= START when start_load = '1' else IDLE;
	read_START_next <= WAITING when M_AXI_ARREADY = '1' else START;
	read_WAITING_next <= ACCEPT when M_AXI_RVALID = '1' else WAITING;
	read_ACCEPT_next <= IDLE;

	--internal signals
	Load_data_en <= '1' when read_cur_state = ACCEPT else '0';
	--Bus outputs
	M_AXI_ARVALID <= '1' when read_cur_state = START else '0';
	M_AXI_RREADY <= '1' when read_cur_state = ACCEPT else '0';
	--external outputs
	load_done <= '1' when read_cur_state = ACCEPT else '0';

	--format load_store_out
	with address(1 downto 0) select pre_load_data <=
		(31 downto 8 => '0') & load_data(15 downto 8) when "01",
		(31 downto 8 => '0') & load_data(31 downto 24) when "11",
		(31 downto 16 => '0') & load_data(31 downto 16) when "10",
		load_data when others;

	with load_store_type select load_data_out <=
		(31 downto 8 => pre_load_data(7)) & pre_load_data(7 downto 0) when "000",
		(31 downto 16 => pre_load_data(15)) & pre_load_data(15 downto 0) when "001",
		(31 downto 8 => '0') & pre_load_data(7 downto 0) when "100",
		(31 downto 16 => '0') & pre_load_data(15 downto 0) when "101",
		pre_load_data when others; --"010"

	------------------------------
	-- Write Address Channel
	------------------------------
	----------------------------------
	--Write Data Channel
	----------------------------------
	----------------------------------
	--Write Response Channel
	----------------------------------
	--constant outputs
	M_AXI_AWID <= (others => '0');
	M_AXI_AWADDR <= address;
	M_AXI_AWLEN <= "00000000";
	M_AXI_AWSIZE <= '0' & load_store_type(1 downto 0);
	M_AXI_AWBURST <= "01";
	M_AXI_AWLOCK <= '0';
	M_AXI_AWCACHE <= "0010";
	M_AXI_AWPROT <= "000";
	M_AXI_AWQOS <= "0000";

	with address(1 downto 0) select M_AXI_WDATA <=
		(31 downto 16 => '0') & store_data(7 downto 0) & (7 downto 0 => '0') when "01",
		store_data(7 downto 0) & (23 downto 0 => '0') when "11",
		store_data(15 downto 0) & (15 downto 0 => '0') when "10",
		store_data when others;
	with address(1 downto 0) select byte_mask <=
		"0001" when "00",
		"0010" when "01",
		"0100" when "10",
		"1000" when others; --"11"
	half_mask <= "0011" when address(0) = '0' else "1100";
	with load_store_type(1 downto 0) select M_AXI_WSTRB <=
		byte_mask when "00",
		half_mask when "01",
		"1111" when others;
	M_AXI_WLAST <= '1'; --only 1 burst tranactions so always last

	--memory
	store_cur_state <= store_next_state_final when rising_edge(M_AXI_ACLK);
	store_next_state_final <= IDLE when M_AXI_ARESETN = '0' else store_next_state_i;
	--next state
	with store_cur_state select store_next_state_i <=
		store_IDLE_next when IDLE,
		store_START_next when START,
		store_WAITING_next when WAITING,
		store_ACCEPT_next when others; --accept

	store_IDLE_next <= START when start_store = '1' else IDLE;
	store_START_next <= WAITING when M_AXI_AWREADY = '1' else START;
	store_WAITING_next <= ACCEPT when M_AXI_WREADY = '1' else WAITING;
	store_ACCEPT_next <= IDLE when M_AXI_BVALID = '1' else ACCEPT;

	--Bus outputs
	M_AXI_AWVALID <= '1' when store_cur_state = START else '0';
	M_AXI_WVALID <= '1' when store_cur_state = WAITING else '0';
	M_AXI_BREADY <= '1' when store_cur_state = ACCEPT else '0';

	--external outputs
	store_done <= '1' when store_cur_state = IDLE else '0';

	----error
	Error <= '1' when M_AXI_RRESP(1) = '1' or M_AXI_BRESP(1) = '1' else '0'; --both errors have RRESP bit 1 as high

end implementation;
